# Generated by Django 4.2.14 on 2024-07-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_items', '0002_alter_folder_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='name',
            new_name='folderName',
        ),
    ]
