# Generated by Django 4.2.14 on 2024-07-23 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('new_items', '0004_folder_folderuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folderUser',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
