# Generated by Django 4.2.14 on 2024-07-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
