# Generated by Django 4.2.14 on 2024-07-25 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fileUser',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='drive.folder'),
        ),
        migrations.AlterField(
            model_name='innerfolder',
            name='folderUser',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='drive.folder'),
        ),
    ]
