# Generated by Django 4.2.14 on 2024-07-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0006_file_fileuser_alter_innerfolder_folderuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
