# Generated by Django 4.2.14 on 2024-07-26 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drive', '0007_file_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='fileUser',
        ),
        migrations.AddField(
            model_name='file',
            name='folderUser',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
