# Generated by Django 4.2.14 on 2024-07-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0008_remove_file_fileuser_file_folderuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='fileName',
        ),
    ]
