# Generated by Django 4.2.14 on 2024-07-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0009_remove_file_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='folderUser',
            new_name='fileUser',
        ),
    ]
