# Generated by Django 4.2.14 on 2024-07-26 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drive', '0010_rename_folderuser_file_fileuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folderUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
