# Generated by Django 4.2.14 on 2024-07-27 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0011_alter_folder_folderuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innerfolder',
            name='folderUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.folder'),
        ),
    ]
