# Generated by Django 4.2.14 on 2024-07-27 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drive', '0013_alter_folder_foldername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fileUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='folderName',
            field=models.CharField(default='Folder', max_length=50),
        ),
        migrations.AlterField(
            model_name='innerfolder',
            name='folderName',
            field=models.CharField(default='Folder', max_length=50),
        ),
    ]
