# Generated by Django 4.2.14 on 2024-07-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0015_alter_folder_foldername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folderName',
            field=models.CharField(default='Folder', max_length=50),
        ),
    ]
